export {default as Home} from './Home/Home'
export {default as Admin} from './Admin/Admin'
export {default as Cart} from './Cart/Cart'
export {default as OrderHistory} from './OrderHistory/OrderHistory'
export {default as Contact} from './Contact/Contact'